### ISSUE TITLE
SubstitutionModels.jl

### ISSUE THREAD

**Issue by jangevaare** [camilogarciabotero/BioMarkovChains.jl#1]
Hello, I came across your package on the new packages feed. Taking a glance I'm wondering if there's any way in which you might leverage [SubstitutionModels.jl](https://github.com/BioJulia/SubstitutionModels.jl) for this work, or missing features you'd like to contribute to SubstitutionModels.jl.

Cheers,
Justin

**Comment by camilogarciabotero** [comment]
Hi Justin,

I was actually trying to make `BioMarkovChains.jl` compatible with  [SubstitutionModels.jl](https://github.com/BioJulia/SubstitutionModels.jl) in the latest [commit](https://github.com/camilogarciabotero/BioMarkovChains.jl/commit/c35b658aafdf7226f2453f4d98d4dc6425f83aff) where I change a little bit the `initials_distribution` method output... Anyway I want to explore the `Q` and `P` from the `SubstitionModels.jl` methods and extend some functionalities! Any suggestion is welcome, by the way. I am also planning to use some methods from [`MarkovChainsHammer.jl`](https://github.com/sandreza/MarkovChainHammer.jl) see the methods to generate sequences `perronfrobenius` and `generatedna` [here](https://github.com/camilogarciabotero/BioMarkovChains.jl/blob/main/src/perronfrobenius.jl) this is undocumented for now.

Thanks for pining on this!

**Comment by jangevaare** [comment]
No suggestions at this time, just wanted to make a note here early in your package development that there may be some opportunity in case it wasn't already on your radar. 

The SubstitutionModels.jl package has been quiet last couple years but it's also simple and stable. I'm sure it could use some dependency updates. If you run into any issues let me know.

**Comment by camilogarciabotero** [comment]
Ok, that's on the radar for sure. Thank you!
